# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Route-UIKit-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Route-UIKit', :path => '../'
  # Pods for Route-UIKit-Demo

end
